package problems;

public class ProblemSet {
  /**
   *
   * @param m1
   * @param m2
   * @param ceiling
   * @return
   */
  public int problem001(int m1, int m2, int ceiling) {
    /*
     * Problem 1: Multiples of 3 and 5
     *
     * If we list all the natural numbers below 10 that are multiples of
     * 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
     *
     * Find the sum of all the multiples of 3 or 5 below 1000.
     *
     */


    /* The naive method would be to iterate through each integer less
     * than 1000 and keep a running total of all that are evenly
     * divisible by either 3 or 5, with O(n) running time.
     *
     * A better approach is to compute the answer as the sum of
     * arithmetic series, i.e. the sum of the multiples of three plus
     * the sum of the multiples of 5. However, any integers that are
     * multiples of 15 will have been added twice, so we need to
     * subtract that sum
     */

    return arithmeticSum(m1, ceiling)
         + arithmeticSum(m2, ceiling)
         - arithmeticSum(m1 * m2, ceiling);

  }

  /**
   *
   * @param divisor
   * @param ceiling
   * @return
   */
  public int problem002(int divisor, int ceiling) {
    /*
     * Problem 2: Even Fibonacci numbers
     *
     * Each new term in the Fibonacci sequence is generated by adding
     * the previous two terms. by starting with 1 and 2, the first 10
     * terms will be:
     *
     *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *
     * By considering the terms in the Fibonacci sequence whose values
     * do not exceed four million, find the sum of the even-valued
     * terms.
     */
    int sum = 0;
    int nLess2 = 0;
    int nLess1 = 1;
    while (true) {
      nLess1 += nLess2;
      nLess2 = nLess1 - nLess2;
      if (nLess1 > ceiling) {
        break;
      }
      if (nLess1 % divisor == 0) {
        sum += nLess1;
      }
    }

    return sum;
  }

/**
 *
 * @param n
 * @return largest prime factor of n
 */

  public Long problem003(long n) {
    /*
     * Problem 3: Largest prime factor
     *
     * The prime factors of 13195 are 5, 7, 13 and 29.
     *
     * What is the largest prime factor of the number 600851475143 ?
     */

    PrimesGenerator primes = new PrimesGenerator();
    Long factor = 1L;
    while (n > 1) {
      // get the next prime number
      factor = primes.next();

      // if the factor is larger than the square root of n, then n is prime
      // and we can just set factor to n
      if (factor > Math.sqrt(n)) {
        factor = n;
      }

      while (n % factor == 0) {
        n = n / factor;
      }
    }

    return factor;
  }

  public long problem005(int n) {
    /*
     * Problem 5: Smallest multiple
     *
     * 2520 is the smallest number that can be divided by each of the
     * numbers from 1 to 10 without any remainder.
     *
     * What is the smallest positive number that is evenly divisible by
     * all of the numbers from 1 to 20?
     */
    PrimesGenerator primes = new PrimesGenerator();

    long product = 1;

    while (true) {
      long p = primes.next();
      if (p > n) {
        break;
      }


      /*
      * First pass: for each of the primes less than or equal to n, see
      * which of our numbers has the highest power of two as a factor,
      * and multiply the running product total by that amount
      */

      // high-water mark of the exponent for our current prime
      int exp = 0;

      // cycle through each of the multiples of p up to n and check how
      // many times p will go into it
      for (long number = p; number < n+1; number += p) {
        int count = 0;

        while (number % Math.pow(p, count+1) == 0) {
          count++;
        }
        if (count > exp) {
          exp = count;
        }
      }


      /*
      * second go: way simpler, but only works if all of the numbers up
      * to n are used, i.e. it wouldn't work with some sub-set of
      * numbers, or an arbitrary set of numbers
      */
      /*
      int exp = (int)(Math.log(n) / Math.log(p));
      */


      product *= Math.pow(p, exp);
    }

    return product;
  }



  /*
   * Utility functions
   */

  /**
   *
   * @param step
   * @param ceiling
   * @return
   */
  private int arithmeticSum(int step, int ceiling) {
    int count = (ceiling - 1) / step;
    int largestMultiple = count * step;
    return (largestMultiple + step) * count / 2;
  }
}


